const
  SYSTEM_APP_CREATED      = 'Application created.';
  SYSTEM_APP_TERMINATED   = 'Application terminated.';
  SYSTEM_TASK_STARTED     = 'Task started.';
  SYSTEM_TASK_FINISHED    = 'Task finished.';
  SYSTEM_TASK_COPIED      = 'Task copied.';
  SYSTEM_TASK_DAEMON_BEGIN= 'Task daemon begin service.';
  SYSTEM_TASK_DAEMON_EXIT = 'Task daemon exit.';

  ERROR_TASK_INVALID     = 'Task invalid.';
  ERROR_TASK_INACTIVE    = 'Task inactive.';
